version: "3.9"
services:
  influxdb:
    image: "influxdb:${INFLUXDB_IMAGE_TAG}"
    container_name: influxdb
    expose:
      - 8086
    volumes:
      - influxdb:/var/lib/influxdb2
    restart: always
    networks:
      - speedtest-grafana
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
      - "DOCKER_INFLUXDB_INIT_ORG=internet_speed"
      - "DOCKER_INFLUXDB_INIT_BUCKET=internet_speed"
  speedtest-grafana:
    build: .
    image: speedtest-grafana:1.0.0
    container_name: speedtest-grafana
    depends_on:
      - influxdb
    networks:
      - speedtest-grafana
    environment:
      - "SPEEDTEST_INTERVAL=${SPEEDTEST_INTERVAL}"
      - "SPEEDTEST_SERVER_ID=${SPEEDTEST_SERVER_ID}"
      - "INFLUXDB_HOST=influxdb"
      - "INFLUXDB_PORT=8086"
      - "INFLUXDB_ORG=internet_speed"
      - "INFLUXDB_BUCKET=internet_speed"
      - "INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-config/:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - speedtest-grafana
    networks:
      - speedtest-grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"
      - "INFLUXDB_ORG=internet_speed"
      - "INFLUXDB_BUCKET=internet_speed"
      - "INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"

volumes:
  influxdb:
  grafana-storage:

networks:
  speedtest-grafana:
