version: "3.9"
services:
  influxdb:
    image: "influxdb:${INFLUXDB_IMAGE_TAG}"
    container_name: influxdb
    expose:
      - 8086
    volumes:
      - influxdb:/var/lib/influxdb2
    restart: always
    networks:
      - speeder
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
      - "DOCKER_INFLUXDB_INIT_ORG=speeder"
      - "DOCKER_INFLUXDB_INIT_BUCKET=speeder"
  speeder:
    image: ghcr.io/dbrennand/speeder:latest
    container_name: speeder
    depends_on:
      - influxdb
    networks:
      - speeder
    environment:
      - "SPEEDER_SPEEDTEST_INTERVAL=${SPEEDER_SPEEDTEST_INTERVAL}"
      - "SPEEDER_SPEEDTEST_SERVER_ID=${SPEEDER_SPEEDTEST_SERVER_ID}"
      - "SPEEDER_INFLUXDB_HOST=influxdb"
      - "SPEEDER_INFLUXDB_PORT=8086"
      - "SPEEDER_INFLUXDB_ORG=speeder"
      - "SPEEDER_INFLUXDB_BUCKET=speeder"
      - "SPEEDER_INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-config/:/etc/grafana/provisioning
    depends_on:
      - influxdb
      - speeder
    networks:
      - speeder
    environment:
      - "GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}"
      - "GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}"
      - "INFLUXDB_ORG=speeder"
      - "INFLUXDB_BUCKET=speeder"
      - "INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"

volumes:
  influxdb:
  grafana-storage:

networks:
  speeder:
